AllCops:
  Excludes:
    - public/js/ext/**
    - node_modules/**

LineLength:
  Max: 130

MethodLength:
  Max: 15

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

RegexpLiteral:
  Enabled: false
